### ISSUE TITLE
Show only the favicon on the minified tabs

### ISSUE THREAD

**Issue by jppcel** [bwinton/VerticalTabs#170]
I have a suggestion with i said on the feedback in VerticalTabs on Test Pilot:
When the tabs is minified show only the icons, don't need to show part of title of page, like this screenshot:

![captura de tela de 2016-05-11 10-29-30](https://cloud.githubusercontent.com/assets/3324772/15182564/82b88820-1763-11e6-9cbe-16ddd48919d9.png)

PS: I made any modifications on code to show it in this way, but i prefer to not send this code to a pull request why i think it is not better form.

**Comment by johngruen** [comment]
@jppcel, Hey. So we actually inserted the first few characters of text there based on a bunch of user testing where we discovered that leaving the text around helped people discern between multiple tabs from the same source. We're definitely looking at explanding prefs to include an ultra-compact version...stay tuned.

**Comment by jppcel** [comment]
But the problem can be solved with show a "title" when the people put the cursor on a tab(instantly the people make this), don't needing to open the VerticalTabs panel every time with the cursor is over there.

**Comment by bwinton** [comment]
But that makes everyone wait for each title to show up to figure out which tab they wanted to click on…
(What do you think about being able to re-size the pinned version to only show the icons, though?  That way you could have the icon-only view, and it wouldn't open whenever you moved the cursor over it…)

(Resolving this as wontfix, because we're tracking the resizable sidebar in another bug.)
