### ISSUE TITLE
Suboptimal tab-close function

### ISSUE THREAD

**Issue by oldpainless** [bwinton/VerticalTabs#237]
I like the idea, and I think it will be relatively easy to get used to.

I find it slightly annoying to close tabs. When all I want is to close a tab, I have to move the cursor over the panel and wait for it to expand - first then can I close the tab wo using ctrl+w. Some UI redesign need to make it perfect.

**Comment by bwinton** [comment]
The tricky part here is that we don't want to make it too easy for people to close tabs, otherwise they would close them accidentally while trying to switch to them.  (And I assert that people switch tabs more often than they close them.)

If you have any ideas on how we could make it better, I would love to hear them, but until we have a concrete design, I'm going to mark this closed.

Thanks!  🙂
