### ISSUE TITLE
New tabs should open at the top of the tab list

### ISSUE THREAD

**Issue by phlsa** [bwinton/VerticalTabs#3]
Clicking the new tab button and pressing ctrl-t should open a new tab at the top of the list, pushing all the other tabs down.
All other tab opening behavior can remain untouched.

**Comment by bwinton** [comment]
At the top, but still under any pinned tabs, I'm guessing?

**Comment by phlsa** [comment]
In the long term I think yes, but in the short term pinned tabs are a thing we can simply not support in order to move faster :)

**Comment by bwinton** [comment]
It turns out to be (much) easier to just open all new tabs at the top.  Would that be okay?
(I can probably also do it for only the new tab button, but not ctrl-t, if that's better…)

**Comment by phlsa** [comment]
Hm... we could just open everything at the top as an experiment to user test to get some insight into how people are using that.
Could you implement that behind a pref so that we can A/B test once this is in Test Pilot?

**Comment by bwinton** [comment]
Sure!  :smile:

**Comment by phlsa** [comment]
This doesn't seem to be working anymore...

**Comment by azdle** [comment]
I hope it's not considered mean to thumbs-down an issue, but I really don't like the idea of putting new tabs at the beginning. I apologize for bikeshedding on this, but to me it feels like changing the existing behavior, that has been there since tabs became a thing, for no reason.

If it's really important to have the "new tab" button near where the new tabs are created, I'd much rather see the button float at the bottom of the tab list just like it currently floats at the end of the standard tab list.

**Comment by bwinton** [comment]
We had it as the bottom of the tabs list, and during user testing people couldn't find it, and didn't know how to open new tabs.  You can certainly thumbs-down an issue, but I'm afraid your opinion (and my opinion, for that matter! :wink:) don't hold much weight when compared to data collected from users.

**Comment by jalexandretoledo** [comment]
Could that be optional? I *do* prefer my new tabs at the end of the list.

**Comment by neonhacker** [comment]
I agree that it would be great to have this as an option - some like new tabs to open at the bottom of the list and others like them to open at the top (under pinned tabs).
