### ISSUE TITLE
Height of the bar containing new tab button isn't the same height as main bar in Dev Theme

### ISSUE THREAD

**Issue by CharoSW** [bwinton/VerticalTabs#308]
The extension seems to have the dimensions on the normal theme hardcoded for the bar containing the new tab and pin buttons.  Ideally it should adapt this bars height to match that of the theme being used, be it the normal theme, dev theme or some other theme that uses a custom height.

**Comment by User-47186985** [comment]
I suggested simply putting Tab Center below the main toolbar. I hope the devs can add some options in a future release...

**Comment by bwinton** [comment]
So, I tried this, but it was really hard to get working, and in general we don't want the bar to match the size (because it would be far too large if you enabled the bookmarks bar), so I'm going to close this, because it doesn't seem worth the effort.  (But I would probably accept a patch if someone else wanted to take a stab at it.)  Thanks!
