### ISSUE TITLE
White bar in the between awesomebar and window controls

### ISSUE THREAD

**Issue by jonalmeida** [bwinton/VerticalTabs#319]
Original bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1276990 

Dev Edition Version: 48.0a2 (2016-05-31)

See the screenshot attached regarding the issue of the white space/bar between the awesomebar and the window controls. The bar shows up regardless of the size of the window, and only disappears when in Mac OS X's full screen.

Disabling Tab Center from Flight Test makes the issue go away.

<img width="1456" alt="screen shot 2016-05-31 at 8 56 07 am" src="https://cloud.githubusercontent.com/assets/1370580/15684430/eefbb06c-271b-11e6-8772-b8fa8e4b872e.png">

**Comment by gijsk** [comment]
@bwinton this likely regressed because of https://bugzilla.mozilla.org/show_bug.cgi?id=1273094 and https://bugzilla.mozilla.org/show_bug.cgi?id=1269462 . I would expect that calling `TabsInTitlebar.init()` after your UI is loaded would help. Potentially relevant: https://github.com/jdashg/VerticalTabs/pull/10
