### ISSUE TITLE
Tab Center styles are not overridable

### ISSUE THREAD

**Issue by lopis** [bwinton/VerticalTabs#337]
Since I started using TC, I always made use of my own user style to make it fit my taste. However, I noticed that many styles are not overridable; TC styles always has higher priority and it doesn't matter if my selectors are more specific. Take the following style, for instance - it is completely ignored. I could confirm with the DOM inspector that the selectors and styles are correct, but Firefox simply ignores them.

```
.tabbrowser-tabs .tab-icon-image {
    opacity: 0.5 !important;
}
```

**Comment by ericawright** [comment]
Is this only happening with some styles, or all styles applied to TC? Unfortunately because TC is overriding many inline styles, we also have to use `!important` in  our CSS, I'm sure you are already doing this, but you would need to ensure that your stylesheet is loading last, as well that your selectors are **very** specific.

**Comment by Keith94** [comment]
Try adding `/* AGENT_SHEET */` at the beginning of the stylesheet (tested with Stylish).

**Comment by lopis** [comment]
@ericawright even very specific selectors didn't do the trick.
@Keith94 Adding `/* AGENT_SHEET */` solved it. Thank you!

**Comment by ericawright** [comment]
Great! Thanks @Keith94
