### ISSUE TITLE
Allow nesting of tabs

### ISSUE THREAD

**Issue by futuro** [bwinton/VerticalTabs#371]
## User Story
I'm a developer learning about WebExtensions, and I'm looking at https://developer.mozilla.org/en-US/Add-ons/WebExtensions.Let's call my initial tab Tab Alpha. I start opening tabs for the various children of that page, but they all open as sibling tabs for my initial tab. Let's call that tab set Set A. Because Set A is a sibling to Tab Alpha, I've immediately lost the relation that my workflow started with Tab Alpha and expanded into Set A. When I have many tabs open, encompassing multiple workflows, this is problematic, since I've lost my context, as well as the ability to collapse tab sets for particular workflows.

Let's take this a bit further. As I go into each new tab in Set A, I will find more links that I want to open so I can read them once I'm done on the current tab. Let's call these set of tabs Set AA. Now I have even more tabs in my tab bar, and I've completely lost track of where the tabs in Set A are, since they've mixed in with the tabs in Set AA.

When I want to move to the next tab in Set A, I have to look at every tab between where I am in Set AA and where I want to go in Set A. This will get even more convoluted once I start opening more child tabs from Set A, introducing tab sets Set AB, AC, AD, etc.

## Proposed Feature
Allow the option to nest child tabs beneath their parent, as well as expanding and collapsing tab trees. Some examples of addons that have this functionality include [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) and [Tab Tree](https://addons.mozilla.org/en-US/firefox/addon/tab-tree/)

I didn't see any guidelines for Feature Requests or Issues in the Contributing guide, so if I've missed them please let me know and I'll reformat this request.

**Comment by bwinton** [comment]
This is a great proposal, and I really appreciate the time you've spent on it!  But…
One of the explicit goals of this add-on is to show a simpler interface than Tree Style Tabs, since most people don't really understand (or don't care about) hierarchies in their tabs, so we're not going to implement this feature.  Fortunately, as you mentioned, there are a couple of great add-ons that cover your use-case!

(For reference, the design we're currently targetting is [here](https://mozilla.invisionapp.com/share/GT22ZN6QW#/screens).  It will have tab groups, but no nesting.)

Thanks again for your idea, and I hope you don't mind if I steal your format to add to the Contributing guide.  😉

**Comment by andreykurilin** [comment]
@bwinton hi! 

> since most people don't really understand (or don't care about) hierarchies in their tabs,

What about making it configurable? It will cover more user-groups and instead of several plugins we will have only one.

**Comment by bwinton** [comment]
Welll… it's not really the goal of this add-on, and it would be a large amount of extra code, and while it would cover more people, my gut feeling is that the number of people wouldn't be worth the effort to develop and maintain it.  (In general I think that having more addons that each do a few things well is better than having one add-on try to do everything.)

Having said that, if you get in touch with the developers of Tree Style Tabs, or Tab Tree, feel free to point them my way, and I'll be happy to help them add some of the features of Tab Center to their add-ons!  🙂  (And I won't be at all offended if people choose to use them instead of the one I'm building.  😉)
