### ISSUE TITLE
Vista de las ventanas

### ISSUE THREAD

**Issue by Che234** [bwinton/VerticalTabs#403]
Saludos, espero esten bien

escribo porque me parece mucho mejor para la visa de la nueva barra que, al momento de minimizar las ventanas, se coloque unicamente los favicons (un poco mas grandes) y al momento de agrandar la ventan, es decir, del hover si mostrar el title de cada pagina.
Eso con motivo de mejorar visualmente la barra y que si igual el texto no se va a leer en la vista minima no tiene sentido que este entonces allí cortado.

**Comment by helenvholmes** [comment]
> # Look of the windows

> Hello, I hope you are well

> I'm writing because it appears to me that it would be a lot better for the look of the new bar that, at the moment of minimizing the windows, you only see a larger version of the favicons and then when you hover over them you can see the title of each page.

> This is with the motive of visually improving the bar and it makes sense since the text is not able to be read in the minimized version so there's no point in having a cut version show.

**Comment by bwinton** [comment]
Good idea!  We added the extra couple of characters because we found that the favicon wasn't enough to tell which page you wanted.  But you're right, the extra characters also don't add a lot of information.  So we've recently landed a feature that shows thumbnails of the page (if you have enough space).  It looks like this:
<img width="271" alt="screenshot 2016-07-13 10 17 28" src="https://cloud.githubusercontent.com/assets/159571/16806578/06a021ec-48e3-11e6-9301-dd352fe18a71.png">

Hopefully that's a little closer to what you were thinking of.  🙂
