### ISSUE TITLE
Customize mode is kinda broken.

### ISSUE THREAD

**Issue by bwinton** [bwinton/VerticalTabs#50]
Reported by @madhavaenros.

**Comment by johngruen** [comment]
![screen shot 2016-04-18 at 11 18 16 am](https://cloud.githubusercontent.com/assets/3323249/14609326/537d5a7c-0557-11e6-982c-f1054d75c865.png)

**Comment by 6a68** [comment]
Estimate: medium-hard to hard

When the add-on is installed, and the [Browser Toolbox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox) is open to its console tab, I see a few errors when I enter Customize mode. The most important seems to be this one:

<img width="904" alt="screen shot 2016-04-18 at 5 59 32 pm" src="https://cloud.githubusercontent.com/assets/96396/14625095/eb078074-0594-11e6-9b87-7de3e931529c.png">

This error is thrown when `CustomizeMode.populatePalette` tries to get `window.gNavToolbox.palette`, but comes up empty:

<img width="577" alt="screen shot 2016-04-18 at 6 11 57 pm" src="https://cloud.githubusercontent.com/assets/96396/14625159/87e2d394-0595-11e6-86a5-090b77718789.png">


Based on this comment near the top of `CustomizeMode`, it seems like there's a palette swap that normally happens when the user enters or leaves the customize screen:

<img width="592" alt="screen shot 2016-04-18 at 6 41 14 pm" src="https://cloud.githubusercontent.com/assets/96396/14625136/482c2818-0595-11e6-9a17-fc67fb68557c.png">


So, what exactly is going wrong?

Without this add-on installed, `window.gNavToolbox.palette` corresponds to the element `<toolbarpalette id="BrowserToolbarPalette">`.

With this add-on installed, `window.gNavToolbox.palette` is null.

However, it's a weird situation. I see the BrowserToolbarPalette element defined [inside browser.xul](https://dxr.mozilla.org/mozilla-central/source/browser/base/content/browser.xul#1018), but I don't see it in the XUL DOM, with or without the add-on installed.

Nothing conclusive so far, but because I still don't see a root cause, I'm guessing it will be a rough bug to sort out.
