### ISSUE TITLE
Where do we want to host the add-on

### ISSUE THREAD

**Issue by ckprice** [bwinton/VerticalTabs#79]
@bwinton to start this discussion with some initial thoughts.

**Comment by bwinton** [comment]
So, there are a few options here.  TabCenter is currently being hosted on [my people account](https://people.mozilla.com/~bwinton/TabCenter/).  The other two TestPilot add-ons are being hosted in [an S3 bucket](http://aws.amazon.com/s3/) or two.  We could host them all on [GitHub pages](https://pages.github.com/), or on [AMO](https://addons.mozilla.org/).

Evaluations:
* People has no uptime guarantees, so that's not perfect.
* S3 is okay, but requires an S3 account (which I, at least, don't have).
* GitHub is fine as long as your add-on is on GitHub (which most of them probably are these days).
  * As an added bonus, you could set up something like Travis or CircleCI to automatically build and sign your add-on and update the rdf file whenever you pushed (or whenever you pushed a new tag)…
* AMO would currently let random people find your add-on, which could skew the data.
  * But we might be able to ask the AMO team to add an "unlisted, but still downloadable" option.

**Comment by johngruen** [comment]
Decision: keeping it on people for now...might migrate later
